title: Bigzero
description: Blog
author: Chí ND
logo: /static/img/avatar.png
github: https://github.com/bigz3ro
about: Web developer

baseurl: ""
url: "bigz3ro.github.io"

disqus_shortname: bzr
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
